### ISSUE TITLE
Out of Travis credits

### ISSUE THREAD

**Issue by sgillies** [sgillies/fiona-wheels#23]
My free plan is out of credits. I'll ask Travis support for OSS only credits. Meanwhile, I've created a private copy of this repo in my employer's org and will build on that plan (paid by Mapbox).

**Comment by mattip** [comment]
One way to mitigate this might be to move to building with cibuildwheel on github actions. That will give you direct access to manylinux x86_64 and aarch64 (using qemu), macOS, and windows64 builds, you can even move the wheel building into the main repo.

**Comment by sgillies** [comment]
@mattip yes... though I'm not thrilled about migrating all of multibuild and our extensions https://github.com/sgillies/fiona-wheels/blob/master/config.sh. I've not seen cibuildwheel used for something with as many C dependencies as we have here (GDAL, PROJ, GEOS, and a host of other libs).

**Comment by mattip** [comment]
OK, then the move could be in two steps: move to github actions CI with multibuild to solve the immediate need for CI, then maybe at some point in the future move to cibuildwheel when convenient.
