### ISSUE TITLE
Python 3.13

### ISSUE THREAD

**Issue by sgillies** [sgillies/fiona-wheels#46]
There are 2 different groups of tasks

### Python 3.13 support in CI runners

* [x] Check GHA Windows
* [x] Check GHA Mac
* [x] Check GHA Linux
* [x] Check Cirrus Mac

### Python 3.13 support in wheel building tools

* [x] Check multi-build
* [x] Check cibuildwheel

Conclusions:

* https://github.com/multi-build/multibuild/blob/devel/osx_utils.sh#L24 lacks support for downloading Python 3.13.
* My custom fork of auditwheel needs to be synced with main project, should do this before 1.10.0rc1 anyway.
* Lack of numpy wheels for 3.13 is a blocker on Windows and other platforms surely.

**Comment by EwoutH** [comment]
https://github.com/sgillies/fiona-wheels/pull/48 might help, it will automate updating GitHub Actions, including updating cibuildwheel to the latest version which support Python 3.13.

**Comment by EwoutH** [comment]
> * https://github.com/multi-build/multibuild/blob/devel/osx_utils.sh#L24 lacks support for downloading Python 3.13.

Opened a PR upstream, last year it was merged within the day!

- https://github.com/multi-build/multibuild/pull/522

**Comment by mattip** [comment]
> Lack of numpy wheels for 3.13 is a blocker on Windows

You can get pre-release wheels at https://anaconda.org/scientific-python-nightly-wheels/numpy

**Comment by EwoutH** [comment]
They're are also right on PyPI: https://pypi.org/project/numpy/#files

**Comment by mattip** [comment]
sorry, I meant for next year's 3.14 update effort, the pre-release wheels will be on the staging site before they are released to PyPI.

**Comment by EwoutH** [comment]
Yes that's a good point!

**Comment by sgillies** [comment]
I just saw this https://github.com/multi-build/multibuild/blob/devel/osx_utils.sh#L25 @EwoutH. Nice work!

**Comment by sgillies** [comment]
In conclusion: we can continue with multibuild for the remainder of the 1.10.0 release plan and migrate to cibuildwheel after.
